### PR TITLE
Added possibility to disable CSRF VALIDATION

### PR DESCRIPTION
**Pull request by amreo**
I don't understand how to create a valid csrf token!

### CODE REVIEW

**Comment by adam-hanna** [comment]
CSRF is a very important and basic protection scheme for all web servers. I'd really rather not add an option to disable it.

What have you tried? What errors are you getting?

Checkout the [docs about CSRF](https://github.com/adam-hanna/jwt-auth#3-csrf-secret-string).

Also, checkout the examples. Notice how this example is using a [hidden form field to send the CSRF token](https://github.com/adam-hanna/jwt-auth/blob/master/examples/login_logout_ECDSA/templates/templateFiles/login.tmpl#L20), which it grabs [from the login response header](https://github.com/adam-hanna/jwt-auth/blob/master/examples/login_logout_ECDSA/templates/templateFiles/login.tmpl#L65). From the [docs](https://github.com/adam-hanna/jwt-auth#3-csrf-secret-string), it could have also been sent `in the request header with the key of "X-CSRF-Token", or in the "Authorization" request header with a value of "Bearer " + token.`

**Comment by amreo** [comment]
The problem is that I don't understand how to generate and send a valid CSRF token.

**Comment by adam-hanna** [comment]
The CSRF token gets generated on the server. You don't need to generate it. You need to read it from from the response header and send it with all subsequent requests. See the example I linked, above.

It happens [here](https://github.com/adam-hanna/jwt-auth/blob/3f596e66e003161dc0a4e3cd0a1e26b1e1cf6dfe/jwt/credentials.go#L41)

**Comment by brnck** [comment]
@adam-hanna could you please elaborate how CSRF makes stateless application more secure? What if my application is being used by another application? How CSRF helps if two only applications talk to each other? 

Perhaps author did a great job with a bad motivation, but I strongly recommend take into consideration of accepting this

I found very informative thread on stackexchange about whether CSRF is needed on stateless applications or not. Ref: https://security.stackexchange.com/questions/170388/do-i-need-csrf-token-if-im-using-bearer-jwt

**Pull request closed without merging**
