### PR TITLE
Introduced proper header auth

### PR DESCRIPTION
**Pull request by ruseinov**
@adam-hanna Just in case you want to consider idiomatic way of auth via headers, I like the library, so modified it to better suit single page apps/mobile auth.

### CODE REVIEW

**Comment by adam-hanna** [comment]
Thanks for this. I agree that it should follow standard header keys. I'll update the tests and merge ASAP. Thanks again.

**Comment by ruseinov** [comment]
@adam-hanna No problem!

I'd also recommend to make header names adjustable, as this is crucial for usage behind all sorts of proxies and naming convention in general.

**Comment by adam-hanna** [comment]
Thanks for the suggestions.

I updated the tests and merged with the addition of new options that allow the user to set the auth, refresh and csrf token names.

**Comment by ruseinov** [comment]
Perfect!

**Pull request merged**
